apiVersion: v1
kind: Namespace
metadata:
  name: bank-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: bank-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-api
  template:
    metadata:
      labels:
        app: bank-api
    spec:
      containers:
        - name: app
          image: your-dockerhub-user/bank-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: MONGO_URI
              value: mongodb://mongo.bank-app.svc.cluster.local:27017/bank
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: bank-app
spec:
  selector:
    app: bank-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: bank-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-mongo
  template:
    metadata:
      labels:
        app: bank-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: bank-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: bank-app
spec:
  selector:
    app: bank-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
